name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build App
        run: ci/build-app.sh
      - name: Run Tests
        run: ci/unit-test-app.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Lint:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Lint Code
        uses: super-linter/super-linter/slim@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main